version: 2
registries:
  git-git-mdbootstrap-com:
    type: git
    url: https://git.mdbootstrap.com
    username: piotr@moszkowicz.pl
    password: "${{secrets.GIT_GIT_MDBOOTSTRAP_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: codemaker
    versions:
    - ">= 0"
  - dependency-name: "@jsii/*"
    versions:
    - ">= 0"
  - dependency-name: jsii*
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - ">=11.0.0-0"
  - dependency-name: aws-sdk
    versions:
    - 2.848.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.852.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.858.0
    - 2.859.0
    - 2.860.0
    - 2.861.0
    - 2.862.0
    - 2.863.0
    - 2.864.0
    - 2.865.0
    - 2.866.0
    - 2.867.0
    - 2.868.0
    - 2.869.0
    - 2.871.0
    - 2.872.0
    - 2.873.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.877.0
    - 2.878.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.883.0
    - 2.884.0
    - 2.885.0
    - 2.886.0
    - 2.887.0
    - 2.889.0
    - 2.890.0
    - 2.891.0
    - 2.892.0
    - 2.893.0
    - 2.894.0
    - 2.895.0
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.10.1
    - 0.10.2
    - 0.11.0
    - 0.11.1
    - 0.11.10
    - 0.11.11
    - 0.11.12
    - 0.11.13
    - 0.11.14
    - 0.11.15
    - 0.11.2
    - 0.11.3
    - 0.11.4
    - 0.11.5
    - 0.11.6
    - 0.11.7
    - 0.11.8
    - 0.11.9
    - 0.8.50
    - 0.8.51
    - 0.8.52
    - 0.8.53
    - 0.8.54
    - 0.8.55
    - 0.8.56
    - 0.8.57
    - 0.9.0
    - 0.9.2
    - 0.9.3
    - 0.9.4
    - 0.9.5
    - 0.9.6
    - 0.9.7
  - dependency-name: constructs
    versions:
    - 3.3.36
    - 3.3.37
    - 3.3.41
    - 3.3.43
    - 3.3.44
    - 3.3.45
    - 3.3.47
    - 3.3.48
    - 3.3.49
    - 3.3.50
    - 3.3.53
    - 3.3.54
    - 3.3.55
    - 3.3.58
    - 3.3.59
    - 3.3.61
    - 3.3.62
    - 3.3.63
    - 3.3.64
    - 3.3.65
    - 3.3.66
    - 3.3.67
    - 3.3.68
    - 3.3.69
    - 3.3.70
    - 3.3.71
    - 3.3.72
    - 3.3.74
  - dependency-name: "@types/node"
    versions:
    - 10.17.54
    - 10.17.55
    - 10.17.56
    - 10.17.57
    - 10.17.58
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
    - 9.0.7
    - 9.0.8
    - 9.0.9
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/yargs"
    versions:
    - 16.0.0
  registries:
  - git-git-mdbootstrap-com
